---
archs:
  - ppc64le:
      distro: el8stream
  - s390x:
      distro: el9stream
  - x86_64:
      distro:
        - el8stream
        - el9stream:
            runtime-requirements:
              host_distro: newer

release_branches:
  master:
    - ovirt-master
  ovirt-4.4:
    - ovirt-4.4
